### ISSUE TITLE
Travis Minimal. Job Boost Libraries Missing

### ISSUE THREAD

**Issue by Vince505** [SGpp/SGpp#196]
In my pull request I require a dependency to the boost graph library. In the Travis medium and full jobs all boost libraries seem to be found and used during the compiling, however in the minimal job I realized that in the logs the following messages appear:

Checking for C++ header file boost/test/unit_test.hpp... no
Warning: ****************************************************
         No Boost Unit Test Headers found. Omitting Boost unit tests.
         Please install the corresponding package, e.g., on Ubuntu
         > sudo apt-get install libboost-test-dev
         ****************************************************
Checking for C++ library boost_unit_test_framework... no
Warning: ****************************************************
         No Boost Unit Test library found. Omitting Boost unit tests.
         Please install the corresponding package, e.g., on Ubuntu
         > sudo apt-get install libboost-test-dev
         ****************************************************

I assume that there is maybe something wrong with the configuration of the minimal job that the path to the boost library is not set correctly and therefore the dependency that I need is not pulled and as a result the minimal job fails. (The medium and full travis job execute without any issues)

**Comment by valentjn** [comment]
@Vince505 Sorry, there is nothing wrong with the Travis jobs. The warnings you are seeing is because the minimal job tests successful compilation without installing any other dependencies on a vanilla Ubuntu (that is, besides SCons of course), as SG<sup>++</sup> should successfully even in this case. The Boost.Test library is not needed for successful compilation, but recommended for running the tests ([see also the Wiki](https://github.com/SGpp/SGpp/wiki/Linux-(GCC-Clang-ICC))).

I assume you mean PR #193. [As already stated there](https://github.com/SGpp/SGpp/pull/193#issuecomment-559957219), new code should not introduce new dependencies, especially not on Boost. Experience from people who worked with supercomputers, Windows machines, or other exotic systems with rare system architectures tells that something like this significantly increases the entry barrier. We want SG<sup>++</sup> installation to be as simple as possible. In addition, this increases support overhead for the SG<sup>++</sup> team.

Please find a way of doing what you want without Boost.
