### ISSUE TITLE
GridPrinter::printSparseGrid

### ISSUE THREAD

**Issue by uselessisety** [SGpp/SGpp#4]
Hi guys,
sorry to bother you every day with some new issue :)
I found that the `GridPrinter::printSparseGrid` function is not working (for me). It is only printing out "0" as grid coordinates. 
The `coords` string seems to be correct but the writing of the stringstream into the `tmp` variable seems to fail and produces the zeros.

**Comment by pfluegdk** [comment]
Thanks again for the report. We will check and correct. If it is really urgent, please tell. Otherwise we will correct it in the next release (which should be coming soon anyway).

**Comment by spc90** [comment]
The issue is that the `toString` methods do not simply add spaces between elements of the DataVector, but they also add the parentheses and commas, so it makes a "pretty" output. Therefore the `>>` operator fails to transform what it reads into doubles. 
The solution is simple: iterate through the DataVector and print the values found there directly to file, ditching the stringstream.
